#! /usr/bin/env bash

ALACRITTY=$XDG_CONFIG_HOME/alacritty
THEME_FILE=$(find ~/.config/alacritty/themes/ -name "*.yml" -printf "%f\n" | \
           dmenu)

# Exit if THEME_FILE is empty.
if [ -z $THEME_FILE ]; then
    exit
fi

FIRST_LINE=$(head -n 1 "$ALACRITTY/themes/$THEME_FILE")
cat $ALACRITTY/base-config.yml $ALACRITTY/themes/$THEME_FILE > $ALACRITTY/alacritty.yml

if [[ "$THEME_FILE" == *"dark"* || "$FIRST_LINE" == *"dark"*  ]]; then
    echo "dark" > $ALACRITTY/colorstate
else
    echo "light" > $ALACRITTY/colorstate
fi

# run nvim reload script
reload-nvim-config
