snippet_support = false
verbosity = 2

[server]
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"
offset_encoding = "utf-8"

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
settings_section = "haskell"
[language.haskell.settings.haskell]
# formattingProvider = "ormolu"

[language.nix]
filetypes = ["nix"]
roots = ["flake.nix", "shell.nix", ".git"]
command = "rnix-lsp"

[language.latex]
filetypes = ["latex"]
roots = [".git", ".hg"]
command = "texlab"
settings_section = "texlab"
[language.latex.settings.texlab]
# See https://github.com/latex-lsp/texlab/blob/master/src/options.rs
# bibtexFormatter = "texlab"

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg", "pyproject.tml", "manage.py"]
command = "pylsp"
offset_encoding = "utf-8"
settings_section = "pylsp"
[language.python.settings.pylsp]
pylsp.plugins.pylsp_mypy.enabled = true
pylsp.plugins.pylsp_mypy.live_mode = true
pylsp.plugins.pylint.enabled = true
pylsp.plugins.flake8.enabled = false
pylsp.plugins.mccabe.enabled = false
pylsp.plugins.pycodestyle.enabled = false
pylsp.plugins.pyflakes.enabled = false
pylsp.plugins.yapf.enabled = false
